# Generated by Django 2.2 on 2020-05-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourses',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程信息',
                'verbose_name_plural': '轮播课程信息',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.courses',),
        ),
    ]
