# Generated by Django 2.2 on 2020-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='就职公司'),
        ),
    ]
