# Generated by Django 2.2 on 2020-05-30 07:23

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200528_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='机构描述'),
        ),
    ]
